name: Horusec Scan
 
on: [push]
 
jobs:
  checking_code:
    runs-on: ubuntu-latest
    name: Horusec Scan
    steps:
      - uses: actions/checkout@v3
 
      - name: Run Horusec
        env:
          HORUSEC_CLI_RETURN_ERROR_IF_FOUND_VULNERABILITY: "false"
        id: run_horusec
        uses: fike/horusec-action@v0.2.2
        with:
          arguments: -c=horusec-config.json -p ./ --return-error=true
